const SUPER_ADMIN = 0;
const ADMIN = 1;
const CONTRIBUTOR = 2;
const ALLOWED_VALUE_CODES = [1, 2];

module.exports = {
  SUPER_ADMIN: SUPER_ADMIN,
  ADMIN: ADMIN,
  CONTRIBUTOR: CONTRIBUTOR,
  ALLOWED_VALUE_CODES: ALLOWED_VALUE_CODES,
};
